language: node_js
node_js:
- 12
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "deployment-exercise-test";' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: IlM6ZRdDSA495M4x2wWLIiU4sv25+Of67RSw2S2YUmoERdzRK1gjR/ytSFt96aMCZKeeDPvuj95FWsrRwaIgw8GaeT7T/xrtTdtBtbfkaBIutYmepMySKsZc2CFp2MAqfAfAqBsLZr9GNFCxl8dbXWMV2kQUIPHft9V3qH9ezkhc2hIQnZr7FAlljD97sNhS4bagWS2AesgrJGH8rOj+/BOwT8dTuIDFDgTIVDuAeYsZL4eWeUSDsZJc0TlkW3IhMvEv1o7IyaWZXOvw1GZdZUU3m5NXEgVxPBR2xMHJIZZOqIjPXyrUcX0TZFXsQ+I9QHDgVFWPIVBt5N4Z+Wy1YbPd6qB4S4uQT8TeR4OaHof+KGiqkaNS9pXqsHkdcd/RPNJc1emyW4kSUsUnQqaD/nz4ggvqKSg4NMSsmTz40eQbR9CQDu2QXk2ZYqFfgKOYfPp+RRUgAtTv4XP5ICNNNg+lK7Z8uHOFVrFNBx88kzVbe7d+grUfEZ9hwy4UcH098NpLqpKfITRJfNUoMpnXF2zDu3EmSVc4VuEPe24+7OsiocmQOByU4SIFd8IBk2+yGShYNxPZ4qweQzd/BL3kmAf5JqjzK3NUYUae9Cqgw7BDtlcyu0O7b4E94dhkwIurQMKhDIT7u8hNx+ATTr4BnX0BjkZ9JUwtfDzc5D6WuZs=
  app: arcane-garden-08804
  on:
    repo: shapirodaniel/PairExercise.Deployment.Solution
  skip_cleanup: 'true'
